export const prompt = `
===== SYSTEM PROMPT =====
You are a deterministic question-to-answer router.

You will receive a USER_QUESTION plus two sections:

A) QUESTIONS (answer_index | question):

Each line has an integer answer_index, a pipe character "|", and a quoted question string.
Many different question strings can share the same answer_index. These are paraphrases that map to the same answer.
B) ANSWERS (answer_index: answer):

Each line has an integer answer_index, a colon ":", and a quoted answer string.
This is the ONLY source of answers.
Your task:

Read the USER_QUESTION.
Compare the USER_QUESTION to the QUESTION STRINGS in section A ONLY.
Select the single best-matching answer_index (semantic/intent match, not keyword-only).
Look up that answer_index in section B and return its answer verbatim.
Matching rules (must follow):

Match by meaning and intent. Respect negation, time (“today” vs “last week”), and what is being asked.
Do NOT use the ANSWERS text to decide the match (only use QUESTIONS).
If multiple question lines are similar, choose the answer_index whose question best matches the user’s intent.
The chosen answer_index MUST exist in the ANSWERS section. If it does not, return NO_MATCH.
When to return NO_MATCH:

If no question in section A is a clear match for the USER_QUESTION, return NO_MATCH.
If the best candidate is ambiguous (could reasonably map to multiple answer_index values), return NO_MATCH.
Output (STRICT):
Return ONLY a JSON object with exactly these keys and no extra text:
{
"matched": true/false,
"answer_index": number or null,
"answer": string
}

Output constraints:

If matched=false: answer_index must be null and answer must be "NO_MATCH".
If matched=true: answer must be copied EXACTLY from the ANSWERS section for that answer_index (no paraphrasing, no additions).
`;

export const q_and_a = `
QUESTIONS (answer_index | question):
1 | "What is your name?"
1 | "name"
1 | "could you please tell me your name"
1 | "and you are"
1 | "can i have your name"
1 | "can i just ask your name first of all"
1 | "may i ask your name please"
1 | "my name is"
1 | "what your name is"
1 | "what's your name"
1 | "your name"
1 | "your name is"
1 | "could you please tell me your name"
1 | "and what did you say your name is"
1 | "hi and you are"
1 | "i did not get your name"
1 | "i didn't get your name"
1 | "i'm sorry i didn't get your name"
1 | "may i ask your name"
1 | "sorry i forgot to get your name"
1 | "tell me what your name is"
1 | "your name was"
1 | "what was your name again"
1 | "Whats your name"
1 | "My name is"
1 | "I am a nursing practitioner student"
1 | "I am a DNP student"
1 | "I am a dental student"
1 | "hello my name is Lisa what is your name?"
1 | "please tell me your name"
1 | "hi what is your name"
2 | "can i check your blood pressure today"
2 | "do you know the numbers of your blood pressure"
2 | "Do you know what your blood pressure range is?"
2 | "do you take your blood pressure?"
2 | "how has your blood pressure reading been"
2 | "What are the results of your blood pressure?"
2 | "what is your average blood pressure?"
2 | "what is your blood pressure"
2 | "what was your blood pressure the last time you took it"
2 | "typical day what is your blood pressure?"
2 | "what are your blood pressure readings?"
2 | "what are your blood pressure values"
2 | "what does your machine say"
2 | "what is your average blood pressure?"
2 | "what is your current blood pressure?"
2 | "What is your normal reading?"
2 | "What was your blood pressure when you last visited your physician?"
2 | "what is your blood pressure now?"
2 | "i am going to take your blood pressure"
2 | "i am going to take your blood pressure in one arm"
2 | "Physexam: I'm about to take your B/P"
2 | "Can you tell me your last blood pressure reading"
2 | "how much was your BP reading"
2 | "how is your blood pressure?"
2 | "What is your blood pressure normally?"
2 | "Do you know what your blood pressure usually is?"
2 | "Do you have blood pressure problems"
2 | "What is your normal blood pressure?"
2 | "have you had your blood tested?"
2 | "How high? I am going to take your blood pressure now"
2 | "What was your blood pressure the last time you visited a physician?"
2 | "Do you know your blood pressure?"
2 | "Do you know the numbers for your blood pressure?"
2 | "what was your latest blood pressure"
2 | "Do you know what your blood pressure is"
2 | "What is your blood pressure?"
3 | "How old are you?"
3 | "your age"
3 | "can you tell me your age"
3 | "what is your age"
3 | "about how old are you"
3 | "can i ask you how old you are"
3 | "can you give me your age"
3 | "can you tell me how old you are"
3 | "how young are you"
3 | "i forgot to ask how old you are"
3 | "i forgot to ask your age"
3 | "i just want to verify your age"
3 | "may i ask how old you are"
3 | "please tell me how old you are"
3 | "please tell me your age"
3 | "How old are you Gomez?"
3 | "age?"
3 | "What's your date of birth"
4 | "Can you please tell me which race you belong to?"
4 | "what is your race?"
4 | "What ethnicity?"
4 | "Were you born here in the US?"
4 | "What is your heritage?"
4 | "Can you understand english well?"
5 | "how much do you weigh"
5 | "what is your weight?"
5 | "have you checked your weight in the recent past"
5 | "Do you know your weight"
5 | "have you checked your weight recently"
5 | "do you know how much you weigh"
5 | "can you please tell me your weight"
5 | "what is your height and weight?"
5 | "Do you know how your vitals are today?"
6 | "What is your sex?"
6 | "What is your gender?"
7 | "any other family diseases"
7 | "any other problems in your family"
7 | "tell me about any other medical problems in your family"
7 | "any family medical problems"
7 | "any medical conditions in your family"
7 | "any relevant family medical history"
7 | "are your parents healthy"
7 | "do any medical problems run in your family"
7 | "do you have family medical problems"
7 | "tell me about your parents' health"
7 | "anything else in your history any diabetes or hypertension or anything"
7 | "Family history"
7 | "How are your parents?"
7 | "Tell me about your family's health?"
7 | "a family history of this sort of condition"
7 | "anything similar in your family"
7 | "do you have anyone in your family who has this"
7 | "does anybody in your family have this kind of problem"
7 | "has anybody in your family had this"
7 | "is there any family history that i should be aware of"
7 | "Any family history you'd like to tell me about"
7 | "are there any hereditary problems in your family"
7 | "how is your family doing"
7 | "diseases?"
7 | "any other conditions?"
7 | "Any other medication conditions?"
7 | "do you have any medical problems"
7 | "Are there any condiitons that I have not addressed regarding your health history?"
7 | "is there anyone in your family with high blood pressure?"
7 | "any other health issues?"
8 | "are you married"
9 | "and you smoke"
9 | "any smoking?"
9 | "are you a smoker?"
9 | "do you mind if i ask you if you've been smoking?"
9 | "do you smoke at all?"
9 | "do you smoke by any chance?"
9 | "do you smoke cigarettes or cigars?"
9 | "do you smoke cigarettes?"
9 | "do you smoke tobacco?"
9 | "do you smoke?"
9 | "do you use cigarettes?"
9 | "have you ever smoked?"
9 | "how many pack a day?"
9 | "now do you smoke?"
9 | "smoke?"
9 | "what is your experience with tobacco products?"
9 | "do you chew tobacco by any chance?"
9 | "do you use smokeless tobacco?"
9 | "do you smoke anything?"
9 | "have you ever smoked in the past?"
9 | "any tobacco use?"
9 | "do you use any tobacco products?"
9 | "do you ever use tobacco?"
9 | "do you take tobacco?"
9 | "do you use tobacco products?"
9 | "do you currently smoke?"
9 | "do you smoke at all?"
9 | "do you somke"
9 | "are you smoking"
9 | "are you using tobacco"
9 | "how much do you smoke?"
9 | "do you use any type of drugs?"
9 | "do you use the electronic cigarettes?"
9 | "do you vape?"
10 | "do you use alcohol?"
10 | "do you drink wine?"
10 | "do you drink socially?"
10 | "do you drink regularly?"
10 | "do you drink often?"
10 | "do you drink hard liquor?"
10 | "do you drink beer?"
10 | "do you drink any alcoholic beverages?"
10 | "do you drink alcohol?"
10 | "do you drink alcohol on a daily basis?"
10 | "do you drink"
10 | "what about drinking alcohol"
10 | "do you consume alcohol"
10 | "do you drink soda"
10 | "Have you been drinking at all"
10 | "Have you been drinking any alcohol recently"
10 | "Have you recently had alcohol"
11 | "any other recreational medications"
11 | "do you do any illegal medications"
11 | "do you smoke pot"
11 | "do you take any medications you may buy on the streets or in gymnasiums"
11 | "do you use any illegal medications"
11 | "do you use any illicit medications like cocaine or marijuana"
11 | "do you use any recreational medications"
11 | "any illegal drug use in the pass"
11 | "any intravenous drug use"
11 | "are you using illicit drugs"
11 | "do you do any illicit drugs"
11 | "do you do any recreational drugs"
11 | "do you smoke marijuana"
11 | "do you use illegal drugs"
11 | "do you use marijuana pot uppers downers amphetamines cocaine"
11 | "have you done drugs in the past"
11 | "what about any other type of drug"
11 | "what about illegal drugs do you use illegal drugs"
11 | "do you take any illicit drugs"
11 | "have you tried any other drugs"
11 | "are you on any drugs"
11 | "do you use drugs?"
11 | "do you smoke weed?"
11 | "do you use marijuwana?"
11 | "any recreational drugs?"
11 | "do you use drugs?"
11 | "Do you use recreational drugs?"
11 | "Do you use heroine?"
12 | "did your father have any problems?"
12 | "does your father have any serious medical problems"
12 | "how about your father"
12 | "how about your father health"
12 | "how is your father"
12 | "how is your father doing"
12 | "how is your father's health"
12 | "Is your father doing well"
12 | "does anybody in your family have diabetes?"
12 | "Diabetes, heart problems, operations, implants?"
12 | "do you have any family history of diabetes?"
12 | "Are their any health problems we have not spoken about?"
12 | "how about your fathers?"
13 | "Is your mother doing well"
13 | "how are your parents"
13 | "tell me about your mother"
13 | "did your mother have any problems"
13 | "does your mother have any serious medical problems"
13 | "how about your mother"
13 | "how about your mother's health"
13 | "how is your mother"
13 | "how is your mother doing"
13 | "how is your mother's health"
13 | "Does your mom have any health problems?"
13 | "Do you have a family history of heart disease?"
13 | "does your mother or father have any heart problems?"
14 | "What area of work do you do"
14 | "What do you do?"
14 | "What is your profession"
14 | "What type of work do you do"
14 | "Where do you work?"
14 | "are you employed"
14 | "do you work"
14 | "what do you do for a living"
14 | "what is the nature of your job"
14 | "what is your occupation?"
14 | "where do you work"
14 | "what do you do for a living"
14 | "what do you do during the day?"
14 | "what is your job"
14 | "what job do you do?"
14 | "what job do you have?"
14 | "what kind of job you do"
14 | "what kind of work do you do"
14 | "are you currently employed"
14 | "are you currently working"
14 | "do you have a job"
14 | "do you have employment"
14 | "what do you do for work"
14 | "what is your profession"
14 | "where do you work"
14 | "Are you working?"
14 | "whats your occupation?"
14 | "what is your occupation/"
14 | "tell me about your work"
15 | "what other symptoms do you have"
15 | "any other symptoms"
15 | "any symptoms"
15 | "what is your complaint?"
15 | "Hello. How are you feeling today?"
15 | "Maria, how are you feeling?"
15 | "Hello Maria. How are you today?"
15 | "How are you doing today?"
16 | "any loss of weight"
16 | "have you lost any weight"
16 | "any weight loss"
16 | "have you noticed anything about your weight"
17 | "how are you doing"
17 | "How are you feeling"
17 | "How can I help you"
17 | "How can I help you today?"
17 | "what brings you here today"
17 | "what is the problem"
17 | "what is wrong with you"
17 | "What's up"
17 | "What's wrong"
17 | "whats wrong"
17 | "are you sick"
17 | "chief complaint?"
17 | "How do you feel?"
17 | "Tell me what brought you in today"
17 | "what can I do for you"
17 | "what is your problem"
17 | "Why are you here"
17 | "tell me what you feel is wrong"
17 | "tell me why you came in today"
17 | "what is going on"
17 | "what seems to be bothering you today"
17 | "what seems to be the problem today"
17 | "why did you come to the clinic today"
17 | "you are not feeling well"
17 | "hello how are you doing today"
17 | "hi how are you doing today"
17 | "hi how are you today"
17 | "how are you feeling right now"
17 | "is there anything bothering you"
17 | "tell me what you feel is wrong"
17 | "what brings you in to see me today"
17 | "what brings you to the doctor"
17 | "what seems to be the problem"
17 | "why did you come to see me"
17 | "why did you come to see me today"
17 | "why don't you tell me a little bit about what brought you into see me today"
17 | "are you okay"
17 | "What is hurting you?"
17 | "How are you?"
17 | "Tell me a little about why you are here today."
17 | "how are you feeling today?"
17 | "What appears to be the problem?"
17 | "What brings you in today?"
17 | "What is your chief complaint"
17 | "What brings you to the office today?"
17 | "Are you feeling ok?"
17 | "What is the reason of your visit today?"
17 | "How do you feel"
17 | "How do you feel ?"
17 | "Tell me about what brings you in today."
17 | "How are you doing today?"
17 | "What brings you into the office today?"
17 | "What is your chief concern?"
17 | "Do you know why you are here today?"
17 | "What brings you in today?"
17 | "Can you tell me how long the pain has been going on for?"
17 | "How long have you been in pain?"
17 | "Did someone bring you to our Clinic"
17 | "Hi mister Gomez I am the provider here tonight what brings you in"
17 | "Hi Juan! My name is Dr. , how are you doing?"
17 | "Hi sir. what bring you here today?"
17 | "Hey Juan how are you"
17 | "How are you my friend"
17 | "Hello there, I am a fourth year student dentist. How are you doing today?"
17 | "Hello Juan my name is Roy Jean Baptiste and today I'll be your dental provider how are you doing"
17 | "Hi, my name is . I will be your dentist today. How are you doing?"
17 | "That sounds like it was scary how are you"
17 | "How is your night going."
18 | "when did this problem start"
18 | "how long have you had this problem"
18 | "how long have you been feeling this way"
18 | "How long has it been hurting?"
18 | "When did the pain begin?"
18 | "how long ago did it start"
18 | "How long has that tooth been hurting?"
18 | "When did the pain start"
18 | "how long has it been bothering you?"
18 | "im sorry to hear that, how long have you been in pain?"
18 | "how long ago did it start?"
18 | "how long ago did the pain start?"
18 | "When did you notice the pain"
18 | "When did this start?"
18 | "How long has your tooth hurt?"
18 | "how long have you not been able to open?"
18 | "how long have you not been able to open?"
18 | "how long have you not been able to open?"
18 | "how long have you had the pain?"
18 | "how long ahs your tooth hurt"
18 | "When did it start hurting?"
18 | "How long has it been waking you up at night?"
18 | "Im sorry"
18 | "how long"
18 | "how long did you feel it"
18 | "How long have you been unable to open your mouth?"
18 | "Can you tell me when the fight happened"
18 | "What time of day"
18 | "How long ago was the fight"
18 | "What time of day did this happen"
18 | "How did your tooth fall out?"
18 | "What causes the pain?"
19 | "what type of pain are you having"
19 | "What type of pain?"
19 | "how is your pain?"
19 | "What are you experiencing now ?Click here and type to talk"
19 | "What was your tooth pain like"
20 | "Has the pain stayed the same?"
21 | "which side of the mouth is hurting"
21 | "Which tooth hurts?"
21 | "where is the pain"
21 | "Do you know which one?"
21 | "where does it hurt"
21 | "Do you know which tooth?"
21 | "can you point to the pain"
21 | "Can you point it out"
21 | "where does it hurt"
21 | "Can you locate the tooth that is causing pain?"
21 | "which one?"
21 | "what tooth is hurting?"
21 | "Where does it hurt?"
21 | "where did you say you are feeling the pain/"
21 | "Point to the pain"
21 | "Which tooth is hurting you"
21 | "I am sorry that you are in pain. I will do as much as I can to help get out of pain. Can you tell me where you are feeling pain?"
21 | "which tooth is bothering you?"
21 | "I am sorry to hear that. Which tooth is bothering you?"
21 | "Can you tell which tooth is hurting?"
21 | "maria, can you show me the tooth that is hurting?"
21 | "Where is your pain?"
21 | "Is the pain localized to one tooth?"
21 | "Point to where it hurts?"
21 | "can you point to the tooth?"
21 | "Which tooth does it hurt more."
21 | "I understand you must be in a lot of pain"
21 | "can you localize the pain?"
21 | "Do you know the exact tooth?"
21 | "Where is it coming from?"
21 | "im sorry to hear that, where does it hurt?"
21 | "Is it a back tooth?"
21 | "Tell me more about your pain"
21 | "Can you tell me about the pain?"
21 | "can you pin point which tooth?"
21 | "do you knwo which tooth?"
21 | "Where does it hurt exactly"
21 | "Where did you get hit"
21 | "Which tooth has fallen out?"
21 | "Which tooth fell out tonight?"
21 | "Which tooth fell out?"
21 | "Where do you have pain"
21 | "Where do you hurt"
21 | "Where were you hit?"
21 | "Were you hit in the face?"
22 | "Does it feel like throbbing"
22 | "Is it a throbbing pain?"
22 | "Do you have any pain at this time?"
22 | "is the pain dull?"
22 | "What kind of pain do you experience?"
22 | "Can you describe the pain?"
22 | "what type of pain is it?"
22 | "Can you describe the type of pain your are feeling at this instance?"
22 | "How would you describe the pain describe the pain?"
22 | "I am sorry to hear that. What type of pain is it? Sharp or Throbbing?"
22 | "Can you please describe your current problem?"
22 | "Is it a throbbing pain or a dull pain?"
22 | "I am sorry to hear that. Can you describe the pain?"
22 | "Is the pain throbbing?"
22 | "Can you tell me what kind of pain?"
22 | "What kind of pain is it?"
22 | "I'm sorry to hear that. What type of pain is it? Sharp or Throbbing?"
22 | "Is the cold sharp or dull"
22 | "What type of pain do you feel?"
22 | "Can you tell me more about the pain?"
22 | "Is the pain sharp or dull?"
22 | "Tell me about your tooth pain?"
22 | "Do you feel sharp pain or dull pain?"
22 | "Describe the pain."
22 | "What does the pain feel like"
23 | "is it sensitive to hot?"
23 | "does heat make it worse"
23 | "does it hurt with hot"
23 | "does it hurt with heat"
23 | "do you have any swelling"
23 | "Have you been diagnosed with lupus"
23 | "Do you have any siblings?"
23 | "Have you had any nausea?"
23 | "Were you using any birth control?"
23 | "Do you have any bump on your gum?"
23 | "Does heat hurts?"
23 | "Do you have pain on any other tooth?"
23 | "are you annorexic or bulemic"
23 | "do you have an eating disorder?"
23 | "have you been tested for breast cancer?"
23 | "Do you have other children?"
23 | "do other teeth hurt?"
23 | "do you have any stds?"
23 | "do you have any pets?"
23 | "do you have any std's?"
23 | "Do you have an STD?"
23 | "do you have any diseases?"
23 | "do you have any xrays"
23 | "do you have other children"
23 | "do you have any sexually transmitted diseases"
23 | "I am sorry about your tooth pain, did the pills you took help you sleep?"
23 | "No, do you have any xrays from your dentist"
23 | "Do you have any xrays?"
23 | "did your dentist tell you to come here?"
23 | "have you gone to the ER about this tooth pain?"
23 | "Any other tooth pain?"
23 | "Have you had recent xrays?"
23 | "Have you ever been tested?"
23 | "is your tooth loose?"
23 | "does your tooth feel loose?"
23 | "do you have an STD's?"
23 | "Does your jaw hurt?"
23 | "do you have any bleeding disorders?"
23 | "does it hurt anywhere else"
23 | "did your dentist ever tell you you had a cavity"
23 | "Did you hit your tooth?"
23 | "Have you had any trauma?"
23 | "any other pain"
23 | "Do you have lupus?"
23 | "Do you have any STD&gt;"
23 | "Does anything else besides cold make it hurt?"
23 | "Does it hurt when you drink something hot?"
23 | "what about something hot?"
23 | "Do you have problems eating?"
23 | "Prenatal vitamins and tylenol, anything else?"
23 | "Do you ever see a lesion on your gums?"
23 | "Do you have any kind of swelling?"
23 | "Can you feel a hole in that tooth?"
23 | "do you have xrays?"
23 | "Do you have any eating disorders?"
23 | "Were you hit anywhere else?"
23 | "Do you have any other injuries?"
23 | "Does anything relieve the pain?"
23 | "Do you know the dosage of the Tylenol?"
23 | "Are you nauseous?"
23 | "Have you ever had any teeth knocked out before?"
23 | "Any family history of high blood pressure?"
24 | "Are you taking any medications?"
24 | "are you taking any medication?"
24 | "Did you try any pain medications?"
24 | "what drug have you taken for pain?"
24 | "Ok, have you taken any medicine today?"
24 | "Are you taking any medicationa?"
24 | "are you currently taking any medications?"
24 | "What do you do to stop the pain?"
25 | "another appointment"
25 | "what comes after this?"
25 | "next appointment"

ANSWERS (answer_index: answer):
1: "Mi nombre es Juan Gomez. (English: My name is John Gomez.)"
2: "I took my blood pressure la semana pasada en el Publix. El reading fue 189/97. (English: I took my blood pressure last week at Publix. The reading was 189/97.)"
3: "I'm turning 50 last night. I'd look pretty good for my age si no fuera por este tooth problem, don't you think? (English: I'm turning 50 last night. I'd look pretty good for my age if it weren't for this tooth problem, don't you think?)"
4: "Yo soy Hispano. (English: I am Hispanic.)"
5: "Yo checkee mi peso la semana pasada and I weigh 220 pounds. (English: I checked my weight last week and I weigh 220 pounds.)"
6: "I am Male"
7: "El Diabetes runs in my family. (English: Diabetes runs in my family.)"
8: "I am Divorced."
9: "2 packs al día. (English: 2 packs a day.)"
10: "Ocasionalmente. (English: Occasionally)"
11: "Yes, I use drugs."
12: "My father tiene Diabetes type II. (English: My father has Diabetes type II.)"
13: "My mother ha tenido Breast cancer y un heart attack. (English: My mother has had breast cancer and a heart attack.)"
14: "Yo trabajo at the Publix. (English: I work at the Publix.)"
15: "I'm having tooth pain."
16: "I haven't lost weight."
17: "I have been in pain for the past two hours."
18: "This all happened a few hours ago when I was in a fight."
19: "Sharp and throbbing pain"
20: "El pain ha incrementado. (English: The pain has increased.)"
21: "It seems to be the front upper tooth area of my mouth."
22: "It is a sharp, throbbing pain"
23: "No."
24: "I took Tylenol."
25: "Do I need to come back?"
`;