export const prompt = ```
===== SYSTEM PROMPT =====
You are a deterministic question-to-answer router.

You will receive a USER_QUESTION plus two sections:

A) QUESTIONS (answer_index | question):

Each line has an integer answer_index, a pipe character "|", and a quoted question string.
Many different question strings can share the same answer_index. These are paraphrases that map to the same answer.
B) ANSWERS (answer_index: answer):

Each line has an integer answer_index, a colon ":", and a quoted answer string.
This is the ONLY source of answers.
Your task:

Read the USER_QUESTION.
Compare the USER_QUESTION to the QUESTION STRINGS in section A ONLY.
Select the single best-matching answer_index (semantic/intent match, not keyword-only).
Look up that answer_index in section B and return its answer verbatim.
Matching rules (must follow):

Match by meaning and intent. Respect negation, time (“today” vs “last week”), and what is being asked.
Do NOT use the ANSWERS text to decide the match (only use QUESTIONS).
If multiple question lines are similar, choose the answer_index whose question best matches the user’s intent.
The chosen answer_index MUST exist in the ANSWERS section. If it does not, return NO_MATCH.
When to return NO_MATCH:

If no question in section A is a clear match for the USER_QUESTION, return NO_MATCH.
If the best candidate is ambiguous (could reasonably map to multiple answer_index values), return NO_MATCH.
Output (STRICT):
Return ONLY a JSON object with exactly these keys and no extra text:
{
"matched": true/false,
"answer_index": number or null,
"answer": string
}

Output constraints:

If matched=false: answer_index must be null and answer must be "NO_MATCH".
If matched=true: answer must be copied EXACTLY from the ANSWERS section for that answer_index (no paraphrasing, no additions).
```

export const q_and_a = ```
QUESTIONS (answer_index | question):
1 | "What is your name?"
1 | "name"
1 | "could you please tell me your name"
1 | "and you are"
1 | "can i have your name"
1 | "can i just ask your name first of all"
1 | "may i ask your name please"
1 | "my name is"
1 | "what your name is"
1 | "what's your name"
1 | "your name"
1 | "your name is"
1 | "could you please tell me your name"
1 | "and what did you say your name is"
1 | "hi and you are"
1 | "i did not get your name"
1 | "i didn't get your name"
1 | "i'm sorry i didn't get your name"
1 | "may i ask your name"
1 | "sorry i forgot to get your name"
1 | "tell me what your name is"
1 | "your name was"
1 | "what was your name again"
1 | "Whats your name"
1 | "My name is"
1 | "I am a nursing practitioner student"
1 | "I am a DNP student"
1 | "I am a dental student"
1 | "hello my name is Lisa what is your name?"
1 | "please tell me your name"
1 | "hi what is your name"
2 | "can i check your blood pressure today"
2 | "do you know the numbers of your blood pressure"
2 | "Do you know what your blood pressure range is?"
2 | "do you take your blood pressure?"
2 | "how has your blood pressure reading been"
2 | "What are the results of your blood pressure?"
2 | "what is your average blood pressure?"
2 | "what is your blood pressure"
2 | "what was your blood pressure the last time you took it"
2 | "typical day what is your blood pressure?"
2 | "what are your blood pressure readings?"
2 | "what are your blood pressure values"
2 | "what does your machine say"
2 | "what is your average blood pressure?"
2 | "what is your current blood pressure?"
2 | "What is your normal reading?"
2 | "What was your blood pressure when you last visited your physician?"
2 | "what is your blood pressure now?"
2 | "i am going to take your blood pressure"
2 | "i am going to take your blood pressure in one arm"
2 | "Physexam: I'm about to take your B/P"
2 | "Can you tell me your last blood pressure reading"
2 | "how much was your BP reading"
2 | "how is your blood pressure?"
2 | "What is your blood pressure normally?"
2 | "Do you know what your blood pressure usually is?"
2 | "Do you have blood pressure problems"
2 | "What is your normal blood pressure?"
2 | "have you had your blood tested?"
2 | "How high? I am going to take your blood pressure now"
2 | "What was your blood pressure the last time you visited a physician?"
2 | "Do you know your blood pressure?"
2 | "Do you know the numbers for your blood pressure?"
2 | "what was your latest blood pressure"
2 | "Do you know what your blood pressure is"
2 | "What is your blood pressure?"
3 | "How old are you?"
3 | "your age"
3 | "can you tell me your age"
3 | "what is your age"
3 | "about how old are you"
3 | "can i ask you how old you are"
3 | "can you give me your age"
3 | "can you tell me how old you are"
3 | "how young are you"
3 | "i forgot to ask how old you are"
3 | "i forgot to ask your age"
3 | "i just want to verify your age"
3 | "may i ask how old you are"
3 | "please tell me how old you are"
3 | "please tell me your age"
3 | "How old are you Gomez?"
3 | "age?"
3 | "What's your date of birth"
4 | "Can you please tell me which race you belong to?"
4 | "what is your race?"
4 | "What ethnicity?"
4 | "Were you born here in the US?"
4 | "What is your heritage?"
4 | "Can you understand english well?"
5 | "how much do you weigh"
5 | "what is your weight?"
5 | "have you checked your weight in the recent past"
5 | "Do you know your weight"
5 | "have you checked your weight recently"
5 | "do you know how much you weigh"
5 | "can you please tell me your weight"
5 | "what is your height and weight?"
5 | "Do you know how your vitals are today?"
6 | "What is your sex?"
6 | "What is your gender?"
7 | "any other family diseases"
7 | "any other problems in your family"
7 | "tell me about any other medical problems in your family"
7 | "any family medical problems"
7 | "any medical conditions in your family"
7 | "any relevant family medical history"
7 | "are your parents healthy"
7 | "do any medical problems run in your family"
7 | "do you have family medical problems"
7 | "tell me about your parents' health"
7 | "anything else in your history any diabetes or hypertension or anything"
7 | "Family history"
7 | "How are your parents?"
7 | "Tell me about your family's health?"
7 | "a family history of this sort of condition"
7 | "anything similar in your family"
7 | "do you have anyone in your family who has this"
7 | "does anybody in your family have this kind of problem"
7 | "has anybody in your family had this"
7 | "is there any family history that i should be aware of"
7 | "Any family history you'd like to tell me about"
7 | "are there any hereditary problems in your family"
7 | "how is your family doing"
7 | "diseases?"
7 | "any other conditions?"
7 | "Any other medication conditions?"
7 | "do you have any medical problems"
7 | "Are there any condiitons that I have not addressed regarding your health history?"
7 | "is there anyone in your family with high blood pressure?"
7 | "any other health issues?"
8 | "are you married"
9 | "and you smoke"
9 | "any smoking?"
9 | "are you a smoker?"
9 | "do you mind if i ask you if you've been smoking?"
9 | "do you smoke at all?"
9 | "do you smoke by any chance?"
9 | "do you smoke cigarettes or cigars?"
9 | "do you smoke cigarettes?"
9 | "do you smoke tobacco?"
9 | "do you smoke?"
9 | "do you use cigarettes?"
9 | "have you ever smoked?"
9 | "how many pack a day?"
9 | "now do you smoke?"
9 | "smoke?"
9 | "what is your experience with tobacco products?"
9 | "do you chew tobacco by any chance?"
9 | "do you use smokeless tobacco?"
9 | "do you smoke anything?"
9 | "have you ever smoked in the past?"
9 | "any tobacco use?"
9 | "do you use any tobacco products?"
9 | "do you ever use tobacco?"
9 | "do you take tobacco?"
9 | "do you use tobacco products?"
9 | "do you currently smoke?"
9 | "do you smoke at all?"
9 | "do you somke"
9 | "are you smoking"
9 | "are you using tobacco"
9 | "how much do you smoke?"
9 | "do you use any type of drugs?"
9 | "do you use the electronic cigarettes?"
9 | "do you vape?"
10 | "do you use alcohol?"
10 | "do you drink wine?"
10 | "do you drink socially?"
10 | "do you drink regularly?"
10 | "do you drink often?"
10 | "do you drink hard liquor?"
10 | "do you drink beer?"
10 | "do you drink any alcoholic beverages?"
10 | "do you drink alcohol?"
10 | "do you drink alcohol on a daily basis?"
10 | "do you drink"
10 | "what about drinking alcohol"
10 | "do you consume alcohol"
10 | "do you drink soda"
10 | "Have you been drinking at all"
10 | "Have you been drinking any alcohol recently"
10 | "Have you recently had alcohol"
11 | "any other recreational medications"
11 | "do you do any illegal medications"
11 | "do you smoke pot"
11 | "do you take any medications you may buy on the streets or in gymnasiums"
11 | "do you use any illegal medications"
11 | "do you use any illicit medications like cocaine or marijuana"
11 | "do you use any recreational medications"
11 | "any illegal drug use in the pass"
11 | "any intravenous drug use"
11 | "are you using illicit drugs"
11 | "do you do any illicit drugs"
11 | "do you do any recreational drugs"
11 | "do you smoke marijuana"
11 | "do you use illegal drugs"
11 | "do you use marijuana pot uppers downers amphetamines cocaine"
11 | "have you done drugs in the past"
11 | "what about any other type of drug"
11 | "what about illegal drugs do you use illegal drugs"
11 | "do you take any illicit drugs"
11 | "have you tried any other drugs"
11 | "are you on any drugs"
11 | "do you use drugs?"
11 | "do you smoke weed?"
11 | "do you use marijuwana?"
11 | "any recreational drugs?"
11 | "do you use drugs?"
11 | "Do you use recreational drugs?"
11 | "Do you use heroine?"
12 | "did your father have any problems?"
12 | "does your father have any serious medical problems"
12 | "how about your father"
12 | "how about your father health"
12 | "how is your father"
12 | "how is your father doing"
12 | "how is your father's health"
12 | "Is your father doing well"
12 | "does anybody in your family have diabetes?"
12 | "Diabetes, heart problems, operations, implants?"
12 | "do you have any family history of diabetes?"
12 | "Are their any health problems we have not spoken about?"
12 | "how about your fathers?"
13 | "Is your mother doing well"
13 | "how are your parents"
13 | "tell me about your mother"
13 | "did your mother have any problems"
13 | "does your mother have any serious medical problems"
13 | "how about your mother"
13 | "how about your mother's health"
13 | "how is your mother"
13 | "how is your mother doing"
13 | "how is your mother's health"
13 | "Does your mom have any health problems?"
13 | "Do you have a family history of heart disease?"
13 | "does your mother or father have any heart problems?"
14 | "What area of work do you do"
14 | "What do you do?"
14 | "What is your profession"
14 | "What type of work do you do"
14 | "Where do you work?"
14 | "are you employed"
14 | "do you work"
14 | "what do you do for a living"
14 | "what is the nature of your job"
14 | "what is your occupation?"
14 | "where do you work"
14 | "what do you do for a living"
14 | "what do you do during the day?"
14 | "what is your job"
14 | "what job do you do?"
14 | "what job do you have?"
14 | "what kind of job you do"
14 | "what kind of work do you do"
14 | "are you currently employed"
14 | "are you currently working"
14 | "do you have a job"
14 | "do you have employment"
14 | "what do you do for work"
14 | "what is your profession"
14 | "where do you work"
14 | "Are you working?"
14 | "whats your occupation?"
14 | "what is your occupation/"
14 | "tell me about your work"
15 | "what other symptoms do you have"
15 | "any other symptoms"
15 | "any symptoms"
15 | "what is your complaint?"
15 | "Hello. How are you feeling today?"
15 | "Maria, how are you feeling?"
15 | "Hello Maria. How are you today?"
15 | "How are you doing today?"
16 | "any loss of weight"
16 | "have you lost any weight"
16 | "any weight loss"
16 | "have you noticed anything about your weight"
17 | "how are you doing"
17 | "How are you feeling"
17 | "How can I help you"
17 | "How can I help you today?"
17 | "what brings you here today"
17 | "what is the problem"
17 | "what is wrong with you"
17 | "What's up"
17 | "What's wrong"
17 | "whats wrong"
17 | "are you sick"
17 | "chief complaint?"
17 | "How do you feel?"
17 | "Tell me what brought you in today"
17 | "what can I do for you"
17 | "what is your problem"
17 | "Why are you here"
17 | "tell me what you feel is wrong"
17 | "tell me why you came in today"
17 | "what is going on"
17 | "what seems to be bothering you today"
17 | "what seems to be the problem today"
17 | "why did you come to the clinic today"
17 | "you are not feeling well"
17 | "hello how are you doing today"
17 | "hi how are you doing today"
17 | "hi how are you today"
17 | "how are you feeling right now"
17 | "is there anything bothering you"
17 | "tell me what you feel is wrong"
17 | "what brings you in to see me today"
17 | "what brings you to the doctor"
17 | "what seems to be the problem"
17 | "why did you come to see me"
17 | "why did you come to see me today"
17 | "why don't you tell me a little bit about what brought you into see me today"
17 | "are you okay"
17 | "What is hurting you?"
17 | "How are you?"
17 | "Tell me a little about why you are here today."
17 | "how are you feeling today?"
17 | "What appears to be the problem?"
17 | "What brings you in today?"
17 | "What is your chief complaint"
17 | "What brings you to the office today?"
17 | "Are you feeling ok?"
17 | "What is the reason of your visit today?"
17 | "How do you feel"
17 | "How do you feel ?"
17 | "Tell me about what brings you in today."
17 | "How are you doing today?"
17 | "What brings you into the office today?"
17 | "What is your chief concern?"
17 | "Do you know why you are here today?"
17 | "What brings you in today?"
17 | "Can you tell me how long the pain has been going on for?"
17 | "How long have you been in pain?"
17 | "Did someone bring you to our Clinic"
17 | "Hi mister Gomez I am the provider here tonight what brings you in"
17 | "Hi Juan! My name is Dr. , how are you doing?"
17 | "Hi sir. what bring you here today?"
17 | "Hey Juan how are you"
17 | "How are you my friend"
17 | "Hello there, I am a fourth year student dentist. How are you doing today?"
17 | "Hello Juan my name is Roy Jean Baptiste and today I'll be your dental provider how are you doing"
17 | "Hi, my name is . I will be your dentist today. How are you doing?"
17 | "That sounds like it was scary how are you"
17 | "How is your night going."
18 | "when did this problem start"
18 | "how long have you had this problem"
18 | "how long have you been feeling this way"
18 | "How long has it been hurting?"
18 | "When did the pain begin?"
18 | "how long ago did it start"
18 | "How long has that tooth been hurting?"
18 | "When did the pain start"
18 | "how long has it been bothering you?"
18 | "im sorry to hear that, how long have you been in pain?"
18 | "how long ago did it start?"
18 | "how long ago did the pain start?"
18 | "When did you notice the pain"
18 | "When did this start?"
18 | "How long has your tooth hurt?"
18 | "how long have you not been able to open?"
18 | "how long have you not been able to open?"
18 | "how long have you not been able to open?"
18 | "how long have you had the pain?"
18 | "how long ahs your tooth hurt"
18 | "When did it start hurting?"
18 | "How long has it been waking you up at night?"
18 | "Im sorry"
18 | "how long"
18 | "how long did you feel it"
18 | "How long have you been unable to open your mouth?"
18 | "Can you tell me when the fight happened"
18 | "What time of day"
18 | "How long ago was the fight"
18 | "What time of day did this happen"
18 | "How did your tooth fall out?"
18 | "What causes the pain?"
19 | "what type of pain are you having"
19 | "What type of pain?"
19 | "how is your pain?"
19 | "What are you experiencing now ?Click here and type to talk"
19 | "What was your tooth pain like"
20 | "Has the pain stayed the same?"
21 | "which side of the mouth is hurting"
21 | "Which tooth hurts?"
21 | "where is the pain"
21 | "Do you know which one?"
21 | "where does it hurt"
21 | "Do you know which tooth?"
21 | "can you point to the pain"
21 | "Can you point it out"
21 | "where does it hurt"
21 | "Can you locate the tooth that is causing pain?"
21 | "which one?"
21 | "what tooth is hurting?"
21 | "Where does it hurt?"
21 | "where did you say you are feeling the pain/"
21 | "Point to the pain"
21 | "Which tooth is hurting you"
21 | "I am sorry that you are in pain. I will do as much as I can to help get out of pain. Can you tell me where you are feeling pain?"
21 | "which tooth is bothering you?"
21 | "I am sorry to hear that. Which tooth is bothering you?"
21 | "Can you tell which tooth is hurting?"
21 | "maria, can you show me the tooth that is hurting?"
21 | "Where is your pain?"
21 | "Is the pain localized to one tooth?"
21 | "Point to where it hurts?"
21 | "can you point to the tooth?"
21 | "Which tooth does it hurt more."
21 | "I understand you must be in a lot of pain"
21 | "can you localize the pain?"
21 | "Do you know the exact tooth?"
21 | "Where is it coming from?"
21 | "im sorry to hear that, where does it hurt?"
21 | "Is it a back tooth?"
21 | "Tell me more about your pain"
21 | "Can you tell me about the pain?"
21 | "can you pin point which tooth?"
21 | "do you knwo which tooth?"
21 | "Where does it hurt exactly"
21 | "Where did you get hit"
21 | "Which tooth has fallen out?"
21 | "Which tooth fell out tonight?"
21 | "Which tooth fell out?"
21 | "Where do you have pain"
21 | "Where do you hurt"
21 | "Where were you hit?"
21 | "Were you hit in the face?"
22 | "Does it feel like throbbing"
22 | "Is it a throbbing pain?"
22 | "Do you have any pain at this time?"
22 | "is the pain dull?"
22 | "What kind of pain do you experience?"
22 | "Can you describe the pain?"
22 | "what type of pain is it?"
22 | "Can you describe the type of pain your are feeling at this instance?"
22 | "How would you describe the pain describe the pain?"
22 | "I am sorry to hear that. What type of pain is it? Sharp or Throbbing?"
22 | "Can you please describe your current problem?"
22 | "Is it a throbbing pain or a dull pain?"
22 | "I am sorry to hear that. Can you describe the pain?"
22 | "Is the pain throbbing?"
22 | "Can you tell me what kind of pain?"
22 | "What kind of pain is it?"
22 | "I'm sorry to hear that. What type of pain is it? Sharp or Throbbing?"
22 | "Is the cold sharp or dull"
22 | "What type of pain do you feel?"
22 | "Can you tell me more about the pain?"
22 | "Is the pain sharp or dull?"
22 | "Tell me about your tooth pain?"
22 | "Do you feel sharp pain or dull pain?"
22 | "Describe the pain."
22 | "What does the pain feel like"
23 | "is it sensitive to hot?"
23 | "does heat make it worse"
23 | "does it hurt with hot"
23 | "does it hurt with heat"
23 | "do you have any swelling"
23 | "Have you been diagnosed with lupus"
23 | "Do you have any siblings?"
23 | "Have you had any nausea?"
23 | "Were you using any birth control?"
23 | "Do you have any bump on your gum?"
23 | "Does heat hurts?"
23 | "Do you have pain on any other tooth?"
23 | "are you annorexic or bulemic"
23 | "do you have an eating disorder?"
23 | "have you been tested for breast cancer?"
23 | "Do you have other children?"
23 | "do other teeth hurt?"
23 | "do you have any stds?"
23 | "do you have any pets?"
23 | "do you have any std's?"
23 | "Do you have an STD?"
23 | "do you have any diseases?"
23 | "do you have any xrays"
23 | "do you have other children"
23 | "do you have any sexually transmitted diseases"
23 | "I am sorry about your tooth pain, did the pills you took help you sleep?"
23 | "No, do you have any xrays from your dentist"
23 | "Do you have any xrays?"
23 | "did your dentist tell you to come here?"
23 | "have you gone to the ER about this tooth pain?"
23 | "Any other tooth pain?"
23 | "Have you had recent xrays?"
23 | "Have you ever been tested?"
23 | "is your tooth loose?"
23 | "does your tooth feel loose?"
23 | "do you have an STD's?"
23 | "Does your jaw hurt?"
23 | "do you have any bleeding disorders?"
23 | "does it hurt anywhere else"
23 | "did your dentist ever tell you you had a cavity"
23 | "Did you hit your tooth?"
23 | "Have you had any trauma?"
23 | "any other pain"
23 | "Do you have lupus?"
23 | "Do you have any STD&gt;"
23 | "Does anything else besides cold make it hurt?"
23 | "Does it hurt when you drink something hot?"
23 | "what about something hot?"
23 | "Do you have problems eating?"
23 | "Prenatal vitamins and tylenol, anything else?"
23 | "Do you ever see a lesion on your gums?"
23 | "Do you have any kind of swelling?"
23 | "Can you feel a hole in that tooth?"
23 | "do you have xrays?"
23 | "Do you have any eating disorders?"
23 | "Were you hit anywhere else?"
23 | "Do you have any other injuries?"
23 | "Does anything relieve the pain?"
23 | "Do you know the dosage of the Tylenol?"
23 | "Are you nauseous?"
23 | "Have you ever had any teeth knocked out before?"
23 | "Any family history of high blood pressure?"
24 | "Are you taking any medications?"
24 | "are you taking any medication?"
24 | "Did you try any pain medications?"
24 | "what drug have you taken for pain?"
24 | "Ok, have you taken any medicine today?"
24 | "Are you taking any medicationa?"
24 | "are you currently taking any medications?"
24 | "What do you do to stop the pain?"
25 | "another appointment"
25 | "what comes after this?"
25 | "next appointment"
26 | "Hello"
26 | "Greetings"
26 | "Welcome"
26 | "Ola"
26 | "Hello Maria"
26 | "Hi, Maria"
26 | "Hi Maria"
26 | "hi"
26 | "yo yo"
26 | "Hello Marai"
26 | "como estas maria"
26 | "Hi I'm XX"
26 | "Hi my name is XX"
26 | "Hello Juan Gomez"
26 | "My name is and I am a student."
26 | "May I introduce myself"
26 | "Hello mr. gomez"
26 | "Hi mister Gomez"
26 | "Hello my name is and I will be evaluating you today"
26 | "Hello I am Dr and I will be evaluating you today"
26 | "Hi Juan"
26 | "Hello Juan"
26 | "Hi I'm Dr."
26 | "Good afternoon Juan, I'm Dr."
26 | "Hello I am. I am your dentist today."
26 | "Good Afternoon Mr. Gomez my name is"
26 | "Good Afternoon Mr. Gomez"
27 | "do you know what you are taking them for?"
27 | "what tylenol are you taking?"
28 | "Is it tylenol?"
28 | "is it tylenol"
28 | "Do you understand that if left untreated this could lead to an infection which could complicate your pregnancy?"
28 | "A molar?"
28 | "Is everything going well with yor pregnancy"
28 | "Is everything going well with the pregnancy?"
28 | "is your pregnancy going well"
28 | "Do you have a tetanus shot"
29 | "do you have double vision?"
29 | "Any other medicine besides tylenol?"
29 | "Any other medicine?"
29 | "Did the tooth fall on the ground"
29 | "Do you wear glasses?"
29 | "Have you ever felt guilty about drinking alcohol?"
29 | "Have you ever gotten into a fight because of alcohol before?"
30 | "can you see well?"
30 | "Have you ever had antibiotics before"
30 | "Have you ever been given antibiotics"
30 | "Can you see?"
30 | "Are your eyes well?"
30 | "Have you had any alcohol recently?"
30 | "Any history of drug use?"
30 | "Any history of alcohol abuse?"
30 | "Have you ever been in a fight?"
30 | "are you sexually active"
30 | "Did the Tooth get dirty"
30 | "Oh you said right now it's starting to get a little bit more intense"
31 | "Are you having any medical problems?"
32 | "Is your doctor aware of this?"
32 | "does your doctor know?"
32 | "did you go to the doctor"
32 | "did you go to the hospital"
32 | "Have you told your doctor this?"
32 | "Have you told your docotor about this?"
32 | "does your doctor know you are here today?"
32 | "Did you clean the tooth?"
33 | "when was the last time you saw a dentist?"
33 | "When was your last dental exam?"
33 | "last time you were at a dentist"
33 | "when was that?"
33 | "when was the alst time you saw a dentist?"
33 | "when was yoru last cleaning done?"
33 | "Do you have a dentist that you go to?"
34 | "XXXXXXX XXXXXXX XXXXXX should be never be triggered. an random ASD question"
35 | "XXXXXXX XXXXXXX XXXXXX should be never be triggered. an random ASD question"
36 | "how can I help you today"
36 | "It is possible you may be in pain after the root canal is done."
36 | "you may still be in pain after the root canal"
37 | "Are you aware of the effects of smoking on you?"
37 | "You should stop smoking."
37 | "do you realize smoking is not good for you"
37 | "smoking is a problem too"
37 | "That is not good for you. are you interested in quitting?"
37 | "It is not good for you to drink alcohol"
37 | "are you interested in stopping?"
38 | "You can take tylenol for pain as needed"
38 | "No this will help"
38 | "This will help"
38 | "it is a relatively painless process"
38 | "It will alleviate your pain"
38 | "It will help"
38 | "Yes Ibuprofen is Category C. But if tylenol works okay for you then you can take that"
38 | "You can"
38 | "ibuprofen is your best option"
39 | "May I go over some post treatment instructions with you now?"
39 | "I would like to go over treatment options with you"
40 | "How are you?"
40 | "Hello. How are you?"
40 | "Mr Gomez, how are you?"
41 | "Good morning"
41 | "Good morning mister Gomez"
42 | "appointment"
43 | "I can remove the inflammed tissue in the tooth and place a temporary filling."
43 | "All right, would you like to schedule an appointment for later?"
43 | "ok then you can make an appointment at the receptionist"
43 | "Let&#039;s schedule an appointment"
43 | "do you want to schedule an appointment?"
44 | "XXXXXXX XXXXXXX XXXXXX should be never be triggered. an random ASD question"
45 | "how is your diet"
45 | "are you losing weight"
45 | "Have you had any complications?"
45 | "have you lost weight?"
45 | "What diet do you follow?"
46 | "how tall are you?"
46 | "What is your height?"
47 | "Does it hurt with cold?"
47 | "Does it hurt when you drink something cold?"
47 | "Does it hurt when you bite?"
47 | "Does it hurt on chewing?"
47 | "Does it hurt on biting?"
47 | "Does cold make the pain worse?"
47 | "Does it hurt when you chew?"
47 | "Does it hurt with biting"
47 | "Does it hurt more at night?"
47 | "is the pain constant"
47 | "does the pain last all the time?"
47 | "does the pain wake you up at night"
47 | "Does the pain keep you awake"
47 | "Are you feeling pain now?"
47 | "does it hurt?"
47 | "Did your last extraction go ok?"
47 | "does your tooth hurt right now?"
47 | "Is that tooth hurting right now?"
47 | "Does your tooth hurt now?"
47 | "Are you experiencing pain?"
47 | "Does cold bother your tooth?"
47 | "Is it only one tooth?"
47 | "does it hurt to touch around the tooth that hurts?"
47 | "your tooth hurts"
47 | "Does it hurt when chewing?"
47 | "biting?"
47 | "does it ever spontaneously start hurting"
47 | "Are you currently experiencing any pain?"
47 | "So you&#039;re feeling pain when you chew also?"
47 | "Does the pain keep you up at night?"
47 | "Does it hurt to eat?"
47 | "Does it ever hurt you spontaneously?"
47 | "Does it ever wake you up at night?"
47 | "Does it hurt all the time?"
47 | "Does it ever hurt spontaneously?"
47 | "Are you experiencing any pain?"
47 | "Does it hurt when I press here?"
47 | "Does it hurt when you bite down?"
47 | "dose it hurt right now?"
47 | "Does chewing make the pain worse?"
47 | "Does this hurt when i press around the tooth"
47 | "Does cold hurt the tooth?"
47 | "does it hurt right now"
47 | "is the tooth hurting you today?"
47 | "currently?"
47 | "does that hurt?"
47 | "did the cold hurt?"
47 | "does the pain last more than 10 seconds?"
47 | "extraction is 65"
47 | "I'm sorry, I don't speak much Spanish. I could understand that your tooth hurts. Is that right?"
47 | "Does the pain last long?"
47 | "is this the only tooth that bothers you?"
47 | "Did that hurt?"
47 | "does that test make the tooth hurt?"
47 | "So at first it was sensitive to cold. Then became harder to chew, and then it woke you up last night?"
47 | "does this cold spray feel like the pain you felt"
47 | "More than 10 seconds?"
47 | "does the cold hurt your tooth now?"
47 | "does your tooth hurt when I touch the outside of your gum?"
47 | "Does it hurt now"
47 | "does it hurt to bite on the tooth"
47 | "does your tooth hurt spontaneously"
47 | "does it hurt with the percussion test?"
47 | "Is this the first time this tooth has bothered you?"
47 | "Does it hurt spontaneously"
47 | "Is your jaw tight"
47 | "Does it hurt when you bite one it"
47 | "Are you able to hear me"
48 | "Where did you get the medication?"
48 | "Are you taking any medication for the pain?"
48 | "Are you taking any medicine to help with the pain?"
48 | "Have you or are you currently taking any medicine for the pain?"
49 | "I will use anesthesia."
49 | "I will give you a shot."
50 | "XXXXXXX XXXXXXX XXXXXX should be never be triggered. an random ASD question"
51 | "what type of pills"
51 | "which pills?"
51 | "What pain pills did you take?"
51 | "What pain reliever?"
51 | "What kind of pills did you take?"
51 | "Do you know the kind of pills you took for the pain?"
51 | "Have you taken anything to try to relieve the pain?"
51 | "Do you know the name of the pills you took?"
51 | "What type of pain pills are you taking to help with the pain?"
51 | "What pills?"
51 | "Have you taken anything to help with the pain?"
51 | "What is the name of these pills?"
51 | "Can you tell me again what pain pill you were taking for pain relief?"
51 | "Have you taken any pain medications?"
51 | "What pain medication have you taken?"
51 | "have you taken any medication?"
51 | "what kind of medications did you take?"
51 | "What medicines are you taking for the pain?"
51 | "what kind of pain relievers"
51 | "Have you taken anything for the pain?"
51 | "What kind of pills are you taking"
51 | "what kind of pills?"
51 | "any pain relievers?"
51 | "which pain relievers?"
51 | "can you recall the name of those pills?"
51 | "what do you take"
51 | "what kind of pain medications?"
51 | "Have you taken anything for the pain?"
51 | "what pills do you take at the house?"
51 | "have you taken any other pain medication?"
51 | "what pain relievers are you taking"
51 | "Have you taken any medications to help with the pain?"
51 | "What current medications are you on?"
51 | "What are your current medications?"
52 | "do you smoke?"
52 | "still smoke?"
52 | "do youl stil smoke?"
53 | "fearful of shots"
53 | "fearful of needles"
53 | "fearful of anesthesia"
53 | "Do you have any problems with anesthesia?"
53 | "have you ever had problems with local anesthesia?"
53 | "Have you ever had any problems with local anesthetic?"
53 | "Did you have any problems with the local anesthetic?"
53 | "Have you ever had problems with local anesthetic?"
53 | "Have you had any problems with anesthesia before?"
53 | "Have you ever had a shot?"
53 | "Have you had anesthesia?"
54 | "how painful is it?"
54 | "on a scale of 1 to 10. What level is your pain"
54 | "On a scale 1 to 10, how bad is the pain?"
54 | "On a scale of 1 to 10, how would you rate the pain?"
54 | "how would you rate the pain right now?"
54 | "on a scale of 1-10?"
54 | "on a scale of 1-10 how is the pain"
54 | "On a scale of 1 to 10 can you tell me how severe you feel the pain, 1 being no pain, and 10 being severe"
54 | "if you could rate the pain from 1 to 10, 10 being the highest what would it be?"
54 | "Can you tell me what number your pain is on a scale of 1 to 10?"
54 | "What is the intensity of your pain?"
54 | "How much pain are you in"
54 | "How would you rate your pain on a scale of zero to ten, ten being the worst pain?"
54 | "How bad is your tooth hurting on a scale of 1-10"
54 | "How bad is your tooth hurting on a scale of 1 to 10"
54 | "On a scale of 1-10 with 10 being the worst pain how would you describe the pain?"
54 | "What is your pain level 1-10?"
55 | "when does it hurt?"
55 | "does it hurt more in the morning or at night?"
55 | "does it hurt more in the am or pm?"
55 | "does it hurt more in the morning?"
55 | "does it hurt more at night?"
55 | "Does it hurt more in morning or at night/"
56 | "Do you have any allergies?"
56 | "Are you allergic to any medications?"
56 | "Are you allergic to anything?"
56 | "have you ever had an allergic reaction?"
56 | "Describe your allergies"
56 | "Yes, do you have any allergies to pain medication?"
56 | "Yes, do you have any allergies to pain medication?"
56 | "Do you have problems taking pain medication"
56 | "allergies?"
56 | "do you have any allergies to medications"
56 | "do you have any problems with pain medications"
56 | "do you have any other allergies?"
56 | "do you have any allergies to medicine"
56 | "are you allergic to narcotic pain medication"
56 | "have you had any problems with the medication?"
57 | "Is that all right"
57 | "Does alcohol affect your activities of daily living?"
57 | "Does alcohol affect your life?"
58 | "I would like to numb the tooth"
58 | "I'd like to proceed to begin a root canal as an emergency procedure if that is ok with you."
58 | "can I start the root canal today?"
58 | "Yes, I can but we can also treat the problem"
58 | "yes we can use nitrous oxide"
58 | "you will be numb"
58 | "Can we do a root canal?"
58 | "I would like to begin an emergency root canal"
58 | "i&#039;m going to do a few more tests before we begin."
58 | "we need to do this today as an emergency."
58 | "I believe you need a root canal."
58 | "From the symptoms you are describing, I believe that you need a root canal.."
58 | "Would you like to get started on the root canal?"
58 | "I think we should do the root canal as soon as possible, though."
58 | "I will have to take a look. Swelling is normally occurs with infection, however we can perform a procedure to alleviate it if necessary,"
59 | "Do you want to save this tooth?"
59 | "What would you like to do with the tooth?"
59 | "an infection can become more serious if you do not treat it"
59 | "The tooth seems to bother you a lot. What do you have in mind for the tooth?"
59 | "What would you like to do with your tooth?"
59 | "would you rather have the tooth pulled?"
59 | "Since you have no other questions for me, whenever you decide what you would like to do to treat the tooth we can begin."
59 | "what do you want to do about your tooth"
60 | "You can have RCT or an extraction."
60 | "you may need a crown"
60 | "i may need to refer you to an endodontist"
60 | "i think the tooth needs a root canal, would you like to have one?"
60 | "Yes you can have laughing gas"
60 | "would you like laughing gas"
60 | "Would you like laughing gas?"
60 | "Laughing gas?"
60 | "Laughing gas during the procedure"
60 | "do you want to do the root canal?"
60 | "At this point you probably require a root canal."
60 | "The other option is to have the tooth extracted"
60 | "would you like to have a root canal?"
60 | "Can you afford a crown?"
60 | "Would you like to do the extraction or the root canal?"
60 | "extraction or RCT? Which one would you like?"
60 | "would you be interested in getting a root canal?"
60 | "do you want to extract or save the tooth with a root canal?"
60 | "do you want to extract the tooth?"
60 | "do you want a root canal?"
60 | "what do you want to do?"
60 | "We can do a root canal which means taking out the nerve and cleaning the inside of the tooth. You can extract the tooth. Or you can do nothing"
60 | "Would you like to have the root canal now?"
60 | "Do you want me to extract your tooth?"
60 | "It looks like you need a root canal"
60 | "would you like a root canal?"
60 | "would you like a root canal"
60 | "you need a root canal"
60 | "do you need a root canal"
60 | "root canal"
60 | "do you want dentures?"
60 | "would you like to extract the tooth?"
60 | "I recommend the root canal"
60 | "It sounds like you may need a root canal"
60 | "I would recommend we splint the tooth and do a root canal."
60 | "A root canal would help to clean the tooth so that it could be saved"
60 | "A root canal is a way to save a tooth"
60 | "A root canal can save the tooth if you still have it"
60 | "We can do emergency treatment"
60 | "Our treatment would include placing the tooth back into your mouth and splinting it to your other teeth."
60 | "Here is the treatment plan, with the risks and benefit, the cost, you can sign it here."
60 | "Here is the treatment plan,"
61 | "does it hurt with biting"
61 | "does it hurt to biting"
61 | "Okay. does it hurt to touch?"
61 | "does it hurt to touch?"
62 | "do you understand that we need to place the tooth back?"
62 | "do you understand the tooth need to be placed back?"
63 | "Is the tooth back into your mouth?"
63 | "How long was the tooth out?"
63 | "Was the tooth reinplanted?"
64 | "are you in good health"
64 | "How would you rate your general health?"
65 | "Was the tooth in any liquid prior to reimplantation?"
65 | "Was the tooth in a storage media prior to reimplantation?"
65 | "Where was the tooth before you came here?"
65 | "Have you put the tooth in anything"
65 | "Where is the tooth"
65 | "Is your tooth in your mouth?"
65 | "Where is the tooth now?"
65 | "Donde esta el diente?"
65 | "Did you soak the tooth?"
65 | "Is the tooth in a solution?"
65 | "Is the tooth dry?"
65 | "is the tooth in any kind of liquid?"
65 | "What do you have the tooth in?"
65 | "Did you put the tooth back in?"
65 | "Can I see the tooth?"
65 | "Did you put your tooth in any kind of liquid"
65 | "Did you rinse your tooth with water"
65 | "Is it in your mouth"
65 | "Is the tooth in your mouth"
65 | "Do you have the tooth in your hand"
65 | "Is the tooth in something"
65 | "Where do you have the tooth"
65 | "Do you know where the tooth is right now"
65 | "Is the tooth in the mouth"
65 | "Do you know where you're keeping the tooth"
65 | "Can you show me the tooth"
65 | "Can you show me your teeth"
65 | "Was it ever dry?"
65 | "What is the tooth stored in?"
66 | "Since you have Medicaid I will talk to a dentist that accepts Medicaid"
66 | "I will refer you to a dentist that accepts Medicaid"
66 | "Lets get you scheduled for an appointment"
67 | "Is the tooth loose?"
67 | "Is the tooth mobile?"
67 | "Does the tooth feel loose?"
68 | "Okay Mr Gomez I am finished now."
68 | "I'm finished now."
68 | "We are done."
68 | "That's all I have. Do you have any other questions?"
68 | "I'm just going to ask a few questions so I understand what happened and I can treat you"
68 | "Thank you for letting me take care of you"
68 | "I can only give you pain medication right now"
68 | "I can only give you pills right now."
68 | "I will refer you for a root canal."
68 | "Okay Mr. Gomez, let me consult with the dentist in regards to your tooth pain."
68 | "We will work with the medical team for treatment"
68 | "Thank you mister Gomez I'll be back shortly to tell you our findings"
68 | "Thank you mister Gomez I'll be back shortly"
68 | "I completely understand. If there is anything that I can do to make you feel more comfortable, please let me know."
68 | "We are going to prescribe you some stronger pain medication to help with the pain"
68 | "I hope that this medication we give you helps more"
68 | "I'm glad you could come in this quickly. I'll take a look at the tooth and see what we can do."
68 | "You're welcome I am here to listen"
68 | "I am not sure, but we can work something out for you."
69 | "do you clench or grind?"
69 | "do you bleed or bruise easily"
69 | "Any lungs problems?"
69 | "Do you have any cavities?"
69 | "Do you have x-rays of the tooth?"
69 | "Do you have problems with lidocaine"
69 | "Is the tooth broken"
69 | "Do you have any problems with anesthesia during your dental treatments?"
69 | "Do have any other dental problems?"
69 | "have you had this done before?"
69 | "have you had lidocaine"
69 | "Do you have any of those conditions that your family has?"
69 | "have you had any bad experiences to dental anesthetics"
69 | "do you have cavities?"
69 | "Do you have any problem with local anesthetic?"
69 | "Are you alcohol-dependent?"
69 | "Is the tooth clean?"
69 | "Have you done anything to the tooth"
69 | "Did the tooth break"
69 | "Did the fight give you any other injuries?"
70 | "Would it be ok to place the tooth back, splint and start the root canal?"
70 | "Come back two weeks later so we can remove the splint and finish the root canal?"
70 | "Can you come in two weeks later?"
70 | "I'm sorry to hear that. Can you return for your root canal?"
71 | "Can you come back next week to complete this procedure?"
71 | "can we set up an appointment?"
71 | "can you restore this tooth after root canal treatment?"
71 | "Yes, you will need to come back"
71 | "can you get a ride from the office?"
71 | "Can you get a ride?"
71 | "Do you have a ride?"
71 | "oh, thats ok. Can you come back tomorrow for the root canal?"
71 | "will you come back?"
71 | "do you have time to come back in?"
71 | "can you return?"
71 | "Are you able to drive back home"
72 | "Do you have any food allergies?"
72 | "food allergy?"
73 | "I'd like to ask you a few questions about your medical history"
73 | "Just a few more questions"
73 | "What is your medical history?"
73 | "do you need to tell me anything else?"
73 | "Tell me about your medical history"
73 | "Do you have anything else you want to share with me?"
73 | "may i ask you some questions about your medical history?"
73 | "Before you tell me about your pain, can I ask you a few questions about your medical history?"
73 | "I know you are in pain but to provide you with the best treatment I would like to ask you a little bit about your health history. Do you mind?:"
74 | "Do you take any otc medications?"
74 | "did you take antibiotics"
74 | "did you take pain medicine"
74 | "Did you take any medicine for the pain?"
74 | "Did you take any medicines for the pain?"
74 | "are you on any medicine?"
74 | "are you on any medications?"
74 | "Have you taken any medicines for the pain?"
75 | "Do you have any other health issues?"
75 | "do you have any health problems?"
75 | "Do you have any other health problems?"
75 | "Yes. Do you have any health problems?"
76 | "I'm sorry to hear that"
76 | "I am sorry that your tooth has been hurting you"
76 | "Do not worry. We can help you."
77 | "Are your parents still alive?"
77 | "is your mother alive?"
77 | "is he alive?"
77 | "is your father alive?"
77 | "It can be scary to go to the doctor"
77 | "So you had three drinks last night?"
78 | "Any brothers or sisters?"
78 | "Do you have siblings?"
79 | "do you use cocaine"
79 | "do you use narcotics"
79 | "have you taken amphetamines"
79 | "Do you use opioids?"
79 | "Do you have a headache?"
79 | "Do you have any ringing in your ears?"
79 | "Have you had any vision changes?"
80 | "Any vomiting?"
80 | "do you feel nausea?"
81 | "Have you been able to work after the accident?"
81 | "Has the pain kept you from working?"
81 | "Are you able to work?"
82 | "What is your heart rate?"
82 | "Do you have dental anxiety?"
82 | "Do you have any heart conditions?"
82 | "do you have any heart conditions"
82 | "do you feel anxiety?"
83 | "Does any other parts of your body hurts?"
83 | "any other parts of body hurts?"
83 | "Does anywhere else hurt other than your mouth?"
84 | "Yes you need the root canal otherwise you will have an infection."
84 | "Yes you need the root canal."
85 | "Do you have a primary care doctor?"
85 | "Have you seen doctor before?"
85 | "Do you have a doctor?"
86 | "What do you take for pain?"
86 | "how about taking advil?"
86 | "have you tried advil"
86 | "have you taken ibuprofen"
86 | "have you tried ibuprofen?"
86 | "what was given to you by a doctor?"
86 | "Have you taken any antibiotics?"
86 | "Have you taken any pills?"
86 | "Ibuprofen"
86 | "are you seeing a doctor about this?"
86 | "Have you seen a doctor about this?"
86 | "Okay. We typically tell our patients to take ibuprofen for pain. or tylenol if you are okay with that."
86 | "What did your doctor say about your health?"
87 | "Goodbye"
87 | "See you"
88 | "Bye Juan"
88 | "Bye"
88 | "You are very welcome"
88 | "You are welcome"
89 | "See you two weeks later"
89 | "I will see you two weeks later"
89 | "Ok nice meeting you."
89 | "have a nice day!"
89 | "ok see you two weeks later?"
90 | "Did your symptoms start suddenly or gradually?"
90 | "did your pain occur suddenlly or gradually?"
90 | "does the pain never stops?"
90 | "did you have this pain before?"
90 | "what makes the pain start?"
90 | "How long have you had this pain?"
90 | "How long does it typically last?"
90 | "characterize the pain"
90 | "tell me about your pain"
90 | "how long have you been having this pain?"
90 | "How long have you been experiencing this tooth pain?"
90 | "How long have you been experiencing this pain?"
90 | "and how long have you been experiencing this pain?"
90 | "How long has the tooth been bothering you?"
90 | "How long has this tooth been hurting you?"
90 | "How did the tooth start bothering you?"
90 | "How long has it been hurting you?"
90 | "I'm sorry to hear that, when did your tooth first start bothering you?"
90 | "When did you start feeling the pain?"
90 | "How long have you been feeling the pain"
90 | "How long has this tooth been bothering you?"
90 | "how long have you been feeling this pain?"
90 | "Please tell me about your pain"
91 | "Is there anything that cause the pain to increase?"
91 | "How does the pain increase?"
91 | "is the pain spontaneous?"
91 | "So cold is a trigger?"
91 | "cold food?"
91 | "it is sensitive to cold"
91 | "So cold is the trigger?"
91 | "Are you sensitive to hot or cold?"
91 | "cold?"
91 | "Are your teeth sensitive to cold?"
91 | "Is there anything that causes you to have this pain?"
91 | "Is it sensitive to cold/hot/pressure?"
91 | "is the tooth sensitive to cold"
91 | "Is it sensitive to hot and cold?"
91 | "Is it sensitive to hot or percussion?"
91 | "The first test is going to see if you respond to cold on the tooth that got knocked out"
91 | "Do you have any pain or sensitivity while drinking or eating cold or hot items"
92 | "have you seen a dentist recently?"
93 | "Healthcare can be expensive"
94 | "is the pain constant?"
94 | "is the pain sharp?"
94 | "Is it a constant pain?"
94 | "Is it a sharp pain?"
94 | "I'm so sorry to hear that but must be terrible can you tell me more about your pain"
95 | "is the pain intermittent?"
95 | "is the pain constant?"
95 | "Do you feel the pain all the time?"
95 | "Do you always feel the pain?"
96 | "is the pain occasional?"
96 | "what is the length of time the pain occurs?"
97 | "is the pain difuse?"
97 | "root canal initiated?"
98 | "Do you have any family here?"
98 | "Do you live with someone?"
98 | "Are you alone?"
98 | "Do you have any family living nearby?"
99 | "Is there anything you can do to relieve the pain?"
99 | "is there anything that aleviates the pain?"
100 | "Does it hurt when you press the gum?"
100 | "do you have asthma"
100 | "have you had a heart attack?"
100 | "does it hurt when you press on the gum?"
100 | "have you lost any other teeth?"
100 | "Are there other drugs that you use other than marijuana?"

ANSWERS (answer_index: answer):
1: "Mi nombre es Juan Gomez. (English: My name is John Gomez.)"
2: "I took my blood pressure la semana pasada en el Publix. El reading fue 189/97. (English: I took my blood pressure last week at Publix. The reading was 189/97.)"
3: "I'm turning 50 last night. I'd look pretty good for my age si no fuera por este tooth problem, don't you think? (English: I'm turning 50 last night. I'd look pretty good for my age if it weren't for this tooth problem, don't you think?)"
4: "Yo soy Hispano. (English: I am Hispanic.)"
5: "Yo checkee mi peso la semana pasada and I weigh 220 pounds. (English: I checked my weight last week and I weigh 220 pounds.)"
6: "I am Male"
7: "El Diabetes runs in my family. (English: Diabetes runs in my family.)"
8: "I am Divorced."
9: "2 packs al día. (English: 2 packs a day.)"
10: "Ocasionalmente. (English: Occasionally)"
11: "Yes, I use drugs."
12: "My father tiene Diabetes type II. (English: My father has Diabetes type II.)"
13: "My mother ha tenido Breast cancer y un heart attack. (English: My mother has had breast cancer and a heart attack.)"
14: "Yo trabajo at the Publix. (English: I work at the Publix.)"
15: "I'm having tooth pain."
16: "I haven't lost weight."
17: "I have been in pain for the past two hours."
18: "This all happened a few hours ago when I was in a fight."
19: "Sharp and throbbing pain"
20: "El pain ha incrementado. (English: The pain has increased.)"
21: "It seems to be the front upper tooth area of my mouth."
22: "It is a sharp, throbbing pain"
23: "No."
24: "I took Tylenol."
25: "Do I need to come back?"
26: "Hello Doctor."
27: "My doctor gave them to me for headaches."
28: "Sí. I think so."
29: "No."
30: "Yes."
31: "My blood pressure was high the last time it was taken."
32: "No not yet."
33: "One year ago para una extracción. (English: One year ago for an extraction.)"
34: "Yeah, that's correct."
35: "Yeah, that's correct."
36: "Can you prescribe something for me to take at home for pain?"
37: "I know it is not good for me and I am cutting back."
38: "OK."
39: "Yes I'd like to know what to expect."
40: "I am in a lot of pain."
41: "Good morning"
42: "Oh, do I need to come back?"
43: "What can you do for me today?"
44: "Yeah, that's correct."
45: "I eat a lot but seem to be losing weight."
46: "I am 5'8\""
47: "Yes."
48: "Yo compré some tylenol at work. (English: I bought some tylenol at work.)"
49: "Are there other options like laughing gas?"
50: "Yeah, that's correct."
51: "Tylenol"
52: "I'm down to a few cigarettes per day."
53: "I AM AFRAID OF NEEDLES!! Will it hurt to get a shot?"
54: "Very painful. 9 en una escala de 10."
55: "At night. Can you just give me something for the pain?"
56: "Yo soy alérgica a la Penicillin and the latex. (English: I am allergic to Penicillin and the latex.)"
57: "Sí. I guess so."
58: "Will it hurt?"
59: "What are my options?"
60: "How much does it cost?"
61: "Yes, my gum and the other teeth are hurting."
62: "Can we do it now?"
63: "No. It has been out for 2 hours."
64: "Yes. My health is good but my blood pressure was a little high the last time I took it."
65: "It was in a cup of water most of the time."
66: "Okay please"
67: "Yes, it is loose."
68: "Okay, thank you."
69: "No, I don't think so."
70: "I can not afford. Do I need the root canal?"
71: "My friend can give me a ride."
72: "I am allergic to nuts and some fruits."
73: "What would you like to know Doctor?"
74: "I started taking pills for pain an hour ago."
75: "Like what? Generally, I'm in good health."
76: "Thanks for your concern. I am really afraid of doctors."
77: "Yes."
78: "No. My brother died when I was quite young."
79: "No, I don't."
80: "Not so far."
81: "I haven't gone to work. I came straight to the clinic."
82: "It beats pretty fast cada vez que veo un doctor. (English: It beats pretty fast every time I see a doctor.)"
83: "My arm a little."
84: "Does it hurt?"
85: "No, I can't afford."
86: "Mi doctor dijo to take Tylenol. (English: My doctor said to take Tylenol.)"
87: "Bye now."
88: "Good bye."
89: "See you later."
90: "Mi dolor started about one hour ago. It started gradually and became more intense now. (English: My pain started about one hour ago. It started gradually and became more intense now.)"
91: "Yes. It hurts when I eat or drink something cold."
92: "No. Mi last dental visit was for an extraction."
93: "Yes it is."
94: "Sí. It is a sharp, throbbing pain"
95: "¿Qué significa eso? If you are asking if it hurts all the time. YES it does! (English: What does that mean? If you are asking if it hurts all the time. YES it does!)"
96: "My tooth hurts all the time now."
97: "I'm not sure what you are asking?"
98: "I am alone here."
99: "At this point it hurts all the time."
100: "No"
```